config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  match '/services', to: 'services#index', via: 'get'

  devise_for :users
  resources :adminkas
  root  'static_pages#home'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

end

app/models/adminka.rb
class Adminka < ActiveRecord::Base
  has_many :attachments
  validates :title, :body, presence: true

  accepts_nested_attributes_for :attachments
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  belongs_to  :adminka
  mount_uploader :file, FileUploader
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data

  validates_presence_of :data
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, :mount_on => :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/adminkas_controller.rb
class AdminkasController < ApplicationController
  before_action :set_adminka, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! , except: [:index, :show]
  # GET /adminkas
  # GET /adminkas.json
  def index
    @adminkas = Adminka.all
  end

  # GET /adminkas/1
  # GET /adminkas/1.json
  def show
  end

  # GET /adminkas/new
  def new
    @adminka = Adminka.new
  end

  # GET /adminkas/1/edit
  def edit
  end

  # POST /adminkas
  # POST /adminkas.json
  def create
    @adminka = Adminka.new(adminka_params)

    respond_to do |format|
      if @adminka.save
        format.html { redirect_to @adminka, notice: 'Adminka was successfully created.' }
        format.json { render :show, status: :created, location: @adminka }
      else
        format.html { render :new }
        format.json { render json: @adminka.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /adminkas/1
  # PATCH/PUT /adminkas/1.json
  def update
    respond_to do |format|
      if @adminka.update(adminka_params)
        format.html { redirect_to @adminka, notice: 'Adminka was successfully updated.' }
        format.json { render :show, status: :ok, location: @adminka }
      else
        format.html { render :edit }
        format.json { render json: @adminka.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adminkas/1
  # DELETE /adminkas/1.json
  def destroy
    @adminka.destroy
    respond_to do |format|
      format.html { redirect_to adminkas_url, notice: 'Adminka was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_adminka
      @adminka = Adminka.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def adminka_params
      params.require(:adminka).permit(:title, :body, attachments_attributes: [:file])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
    @adminkas = Adminka.order(:title)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end
end

app/helpers/adminkas_helper.rb
module AdminkasHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
   def full_title(page_title)
    base_title = "РУСЭМ"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/adminkas/_form.html.erb
<% if current_user.email == 'pkhilenko@yandex.ru'  %>

<%= form_for(@adminka) do |f| %>
  <% if @adminka.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@adminka.errors.count, "error") %> prohibited this adminka from being saved:</h2>

      <ul>
      <% @adminka.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title, 'Название' %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body, 'Описание' %><br>
    <%= f.cktext_area :body %>
  </div>

<div class="field">
   
    <%= f.fields_for :attachments, @adminka.attachments.build do |a| %>
    <%= a.label :file, 'Картинка:' %><br>
    <%= a.file_field :file %>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit 'Добавить' %>
  </div>
<% end %>
<% end %>

app/views/adminkas/edit.html.erb
<h1>изменение "услуга строительной компании"</h1>

<%= render 'form' %>

<%= link_to 'Show', @adminka %> |
<%= link_to 'Back', adminkas_path %>

app/views/adminkas/index.html.erb
<p id="notice"><%= notice %></p>
<% if !user_signed_in? %>
               <strong> <%= link_to "Log in", new_user_session_path %></strong>
              <% else %>
                <strong><%= link_to "Выйти", destroy_user_session_path, method: :delete %></strong>
                <% end %>

<h1>Услуги строительной компании:</h1>
 
 
<table>
  <thead>
    <tr>
      <th>Название</th>
     <!--  <th>Описание</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @adminkas.each do |adminka| %>
      <tr>
        <td><%= adminka.title %></td>
        <!-- <td><%#= adminka.body %></td> -->
        <td><%= link_to 'Показать', adminka %></td>
        <td><%= link_to 'Редактировать', edit_adminka_path(adminka) %></td>
        <td><%= link_to 'Удалить', adminka, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Добавить услугу', new_adminka_path %>

app/views/adminkas/new.html.erb
<h1>Новая услуга строительной компании</h1>

<%= render 'form' %>

<%= link_to 'Back', adminkas_path %>

app/views/adminkas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Название</strong>
  <%= @adminka.title %>
</p>
<p>  
      <% @adminka.attachments.each do |a| %>
        
        <%#= link_to a.file.file.filename, a.file.url %>

        <img src="<%= a.file.url %>"><img>
         
        <% end %>
        
  </p>
<p>
  <strong>Описание</strong>
  <%= @adminka.body.html_safe %>
</p>

<%= link_to 'Изменить', edit_adminka_path(@adminka) %> |
<%= link_to 'Назад', adminkas_path %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    
  </small>
  <nav>
    <ul>
      <li><%= link_to "Главная",    root_path %></li>
              <li><%= link_to "О нас",    about_path %></li>
              <li><%= link_to "Контакты", contact_path %></li>
              <li><%= link_to "Услуги", services_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "СК РусЭМ (3812) 40-69-59", root_path, id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Главная",    root_path %></li>
              <li><%= link_to "О нас",    about_path %></li>
              <li><%= link_to "Контакты", contact_path %></li>
              <li><%= link_to "Услуги", services_path %></li>
            </ul>
          </nav>
        </div>
      </div>
    </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
   <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

      <%= yield %>
      
    </div>
    <div><%= render 'layouts/footer' %></div>
  </body>
</html>

app/views/services/index.html.erb
<h3>Услуги строительной компании:</h3>
<p id="notice"><%= notice %></p>

<h1></h1>

 

  <div>
    <% @adminkas.each do |adminka| %>
      
        <p><strong><%= adminka.title %></strong></p>
      <div>
         
      <% adminka.attachments.each do |a| %>
        <p class="pics">
        <%#= link_to a.file.file.filename, a.file.url %>

        <img  src="<%= a.file.url %>"><img>
        </p>
        <% end %>
        
        <p class="adminka_body"><%= adminka.body.html_safe %><hr /></p>
         </div>
    <% end %>
   
</div>

<br>

app/views/static_pages/about.html.erb
<% provide(:title, 'О нас') %>
<h1>СТРОИТЕЛЬНАЯ КОМПАНИЯ "РУСЭМ"</h1>
<p class="white">................................................</p>
<h2>Руководитель:  Русаков Станислав Васильевич</h2>
<p class="white">................................................</p>
<h3> Телефон/факс (3812) 40-69-59 </h3>
<p class="white">................................................</p>
<h3> Производство общестроительных работ </h3>
<p class="white">................................................</p>

<script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=ctHjS233XpomoXRC5DomqT2PIhoYWYNH&width=600&height=400&lang=ru_RU&sourceType=constructor&scroll=true"></script>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Контакты') %>
<h1>Общество с ограниченной ответственностью «Строительная компания «РусЭМ» (ООО «СК «РусЭМ»)</h1>
<p class="white">................................................</p>
<h2>Телефон/факс: (3812) 40-69-59 </h2>
<p class="white">................................................</p>
<h2>Е-mail: sk-rusm@yandex.ru</h2>
<p class="white">................................................</p>

<script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=ctHjS233XpomoXRC5DomqT2PIhoYWYNH&width=600&height=400&lang=ru_RU&sourceType=constructor&scroll=true"></script>

app/views/static_pages/home.html.erb
<div class="center hero-unit">

  <h1>
    Омская Строительная Компания РусЭМ
   </h1>

   
</div>

<%= image_tag("rusem.jpg", alt: "RUSEM")  %>